import os
import pandas as pd
from multiprocessing import Pool
from Bio import SeqIO

# ==========================
# Globals (shared read-only)
# ==========================
REGISTROS = None
DIFFS = None


def _init_worker(registros, diffs):
    global REGISTROS, DIFFS
    REGISTROS = registros
    DIFFS = diffs


def comparar_secuencia(i):
    record_i = REGISTROS[i]
    grupo = [i]
    seq_i = str(record_i.seq)

    for j in range(i + 1, len(REGISTROS)):
        seq_j = str(REGISTROS[j].seq)
        d = sum(a != b for a, b in zip(seq_i, seq_j))
        if d <= DIFFS:
            grupo.append(j)

    return i, grupo


def pre_cluster_seqs_parallel(
    fasta_path,
    count_table_path,
    diffs=2,
    output_fasta="user_data/outputs/preclustered.fasta",
    output_count="user_data/outputs/preclustered.count_table",
    n_cpus=4
):
    try:
        if not os.path.exists(fasta_path) or not os.path.exists(count_table_path):
            return None, None, "Input files not found."

        # Load sequences
        registros = list(SeqIO.parse(fasta_path, "fasta"))
        registros.sort(key=lambda r: -len(r.seq))

        # 🔑 MAPA ID → ÍNDICE (clave para abundancias)
        id_to_index = {rec.id: i for i, rec in enumerate(registros)}

        usados = set()
        clusters = []

        with Pool(
            processes=n_cpus,
            initializer=_init_worker,
            initargs=(registros, diffs),
            maxtasksperchild=50
        ) as pool:

            for i, grupo in pool.imap_unordered(
                comparar_secuencia,
                range(len(registros)),
                chunksize=10
            ):
                if any(j in usados for j in grupo):
                    continue
                clusters.append([registros[j] for j in grupo])
                usados.update(grupo)

        # Read count table
        df = pd.read_csv(count_table_path, sep="\t")
        df = df.set_index(df.columns[0])

        new_records = []
        new_counts = []

        for idx, cluster in enumerate(clusters):
            new_id = f"precluster_{idx}"
            new_records.append(
                SeqIO.SeqRecord(cluster[0].seq, id=new_id, description="")
            )

            # Sum abundances by POSITION, not by ID
            indices = [id_to_index[c.id] for c in cluster]

            suma = df.iloc[indices].sum()
            suma.name = new_id
            new_counts.append(suma)


        os.makedirs(os.path.dirname(output_fasta), exist_ok=True)
        SeqIO.write(new_records, output_fasta, "fasta")

        new_df = pd.DataFrame(new_counts).reset_index()
        new_df.rename(
            columns={"index": "Representative_Sequence"}, inplace=True
        )
        new_df.to_csv(output_count, sep="\t", index=False)

        return output_fasta, output_count, (
            f"{len(new_records)} sequences generated by pre.cluster "
            f"using {n_cpus} CPU cores."
        )

    except Exception as e:
        return None, None, f"Internal error in pre.cluster: {e}"
